filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - "/logs/*.log"
      - "/workspace/logs/*.log"
      - "/workspace/gateway-service/logs/*.log"
      - "/workspace/logservice/logs/*.log"
      - "/workspace/notificationservice/logs/*.log"
      - "/workspace/servicemanagementservice/logs/*.log"
    exclude_files: ['log-service']
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true

output.kafka:
  hosts: ["172.16.30.15:9092"]
  topic: "app-logs"
  codec.json:
    pretty: false