server:
  port: 8082

spring:
  application:
    name: service-management-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&preparedStatementCacheQueries=0}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.rpnxupaotctyvyqmygdy}
    password: ${SPRING_DATASOURCE_PASSWORD:log-aggregation-10}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false

  security:
    oauth2:
      client:
        registration:
          azure:
            provider: azure
            client-id: ${AZURE_CLIENT_ID:d2801795-44d3-4667-8c21-9df942597dff}
            client-secret: ${AZURE_CLIENT_SECRET:BoT8Q~SEnIlvXIkMWm9EuKZeFUFAoL1XLujaEdzL}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/81a99674-94f7-4f8e-adde-b6affb1d04f7/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/81a99674-94f7-4f8e-adde-b6affb1d04f7/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/81a99674-94f7-4f8e-adde-b6affb1d04f7/discovery/v2.0/keys
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.kovanlabs: INFO

security:
  jwt:
    issuer: service-management-service
    secret: ${JWT_SECRET:change-me-in-prod-change-me-in-prod}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}

app:
  auth:
    oauth-success-redirect: ${AUTH_OAUTH_SUCCESS_REDIRECT:http://localhost:3000/#/login/callback}