CREATE TABLE IF NOT EXISTS alert (
    id UUID PRIMARY KEY,
    service VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    count INT NOT NULL DEFAULT 1,
    severity VARCHAR(30) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
