server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: logservice

  data:
    mongodb:
      uri: mongodb+srv://thaniyarasik:Th%40ni2005@cluster0.37wfqrt.mongodb.net/logs_db?appName=Cluster0
      auto-index-creation: true

  kafka:
    consumer:
      group-id: logservice-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

services:
  management:
    base-url: http://localhost:8082

elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  scheme: ${ELASTICSEARCH_SCHEME:http}
  socket-timeout-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    com.kovanlabs: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"